### ISSUE TITLE
boot project

### ISSUE THREAD

**Issue by guilhermelMoraes** [guilhermelMoraes/my-checklist--back-end#1]
# Todo

- [x] create package.json;
- [x] set up typescript;
- [ ] set up huskylint;
- [ ] set up conventional commits;
- [ ] set up eslint;
- [ ] set up dev enviroment with ts-node and nodemon;
